# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../../defs.bzl", "zs_unittest")

oncall("data_compression")

zs_unittest(
    name = "logger_test",
    srcs = ["LoggerTest.cpp"],
    deps = [
        "../..:logger",
    ],
)
